import { IRecipe } from '../../models/recipe.ts';

export const mockedRecipes: IRecipe[] = [
  {
    id: String(Math.random()),
    imgUrl: './falafel.jpg',
    title: 'Crispy Falafel',
    description: 'Raise your hand if you love falafel! I’ve gone back into the archives...',
  },
  {
    id: String(Math.random()),
    imgUrl: './falafel.jpg',
    title: 'Crispy Falafel',
    description: 'Raise your hand if you love falafel! I’ve gone back into the archives...',
  },
  {
    id: String(Math.random()),
    imgUrl: './falafel.jpg',
    title: 'Crispy Falafel',
    description: 'Raise your hand if you love falafel! I’ve gone back into the archives...',
  },
  {
    id: String(Math.random()),
    imgUrl: './falafel.jpg',
    title: 'Crispy Falafel',
    description: 'Raise your hand if you love falafel! I’ve gone back into the archives...',
  },
  {
    id: String(Math.random()),
    imgUrl: './falafel.jpg',
    title: 'Crispy Falafel',
    description: 'Raise your hand if you love falafel! I’ve gone back into the archives...',
  },
  {
    id: String(Math.random()),
    imgUrl: './falafel.jpg',
    title: 'Crispy Falafel',
    description: 'Raise your hand if you love falafel! I’ve gone back into the archives...',
  },
  {
    id: String(Math.random()),
    imgUrl: './falafel.jpg',
    title: 'Crispy Falafel',
    description: 'Raise your hand if you love falafel! I’ve gone back into the archives...',
  },
  {
    id: String(Math.random()),
    imgUrl: './falafel.jpg',
    title: 'Crispy Falafel',
    description: 'Raise your hand if you love falafel! I’ve gone back into the archives...',
  },
  {
    id: String(Math.random()),
    imgUrl: './falafel.jpg',
    title: 'Crispy Falafel',
    description: 'Raise your hand if you love falafel! I’ve gone back into the archives...',
  },
  {
    id: String(Math.random()),
    imgUrl: './falafel.jpg',
    title: 'Crispy Falafel',
    description: 'Raise your hand if you love falafel! I’ve gone back into the archives...',
  },
  {
    id: String(Math.random()),
    imgUrl: './falafel.jpg',
    title: 'Crispy Falafel',
    description: 'Raise your hand if you love falafel! I’ve gone back into the archives...',
  },
  {
    id: String(Math.random()),
    imgUrl: './falafel.jpg',
    title: 'Crispy Falafel',
    description: 'Raise your hand if you love falafel! I’ve gone back into the archives...',
  },
  {
    id: String(Math.random()),
    imgUrl: './falafel.jpg',
    title: 'Crispy Falafel',
    description: 'Raise your hand if you love falafel! I’ve gone back into the archives...',
  },
  {
    id: String(Math.random()),
    imgUrl: './falafel.jpg',
    title: 'Crispy Falafel',
    description: 'Raise your hand if you love falafel! I’ve gone back into the archives...',
  },
  {
    id: String(Math.random()),
    imgUrl: './falafel.jpg',
    title: 'Crispy Falafel',
    description: 'Raise your hand if you love falafel! I’ve gone back into the archives...',
  },
  {
    id: String(Math.random()),
    imgUrl: './falafel.jpg',
    title: 'Crispy Falafel',
    description: 'Raise your hand if you love falafel! I’ve gone back into the archives...',
  },
  {
    id: String(Math.random()),
    imgUrl: './falafel.jpg',
    title: 'Crispy Falafel',
    description: 'Raise your hand if you love falafel! I’ve gone back into the archives...',
  },
  {
    id: String(Math.random()),
    imgUrl: './falafel.jpg',
    title: 'Crispy Falafel',
    description: 'Raise your hand if you love falafel! I’ve gone back into the archives...',
  },
  {
    id: String(Math.random()),
    imgUrl: './falafel.jpg',
    title: 'Crispy Falafel',
    description: 'Raise your hand if you love falafel! I’ve gone back into the archives...',
  },
  {
    id: String(Math.random()),
    imgUrl: './falafel.jpg',
    title: 'Crispy Falafel',
    description: 'Raise your hand if you love falafel! I’ve gone back into the archives...',
  },
  {
    id: String(Math.random()),
    imgUrl: './falafel.jpg',
    title: 'Crispy Falafel',
    description: 'Raise your hand if you love falafel! I’ve gone back into the archives...',
  },
  {
    id: String(Math.random()),
    imgUrl: './falafel.jpg',
    title: 'Crispy Falafel',
    description: 'Raise your hand if you love falafel! I’ve gone back into the archives...',
  },
  {
    id: String(Math.random()),
    imgUrl: './falafel.jpg',
    title: 'Crispy Falafel',
    description: 'Raise your hand if you love falafel! I’ve gone back into the archives...',
  },
  {
    id: String(Math.random()),
    imgUrl: './falafel.jpg',
    title: 'Crispy Falafel',
    description: 'Raise your hand if you love falafel! I’ve gone back into the archives...',
  },
];
