name: deploy
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: load code
        uses: actions/checkout@v4
      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20.12
      - name: install dependencies
        run: npm ci
      - name: run tests
        run: npm test
